variables:
- name: BuildParameters.RestoreBuildProjects
  value: '**/*.csproj'
- name: BuildParameters.TestProjects
  value: '**/*[Tt]ests/*.csproj'
trigger:
  branches:
    include:
    - refs/heads/master
    - development
    - releases/*
name: $(date:yyyyMMdd)$(rev:.r)
stages:
- stage: build
  jobs:
  - job: Job_1
    displayName: Agent job 1
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: $(BuildParameters.RestoreBuildProjects)
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: $(BuildParameters.RestoreBuildProjects)
        arguments: --configuration $(BuildConfiguration)
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: $(BuildParameters.TestProjects)
        arguments: --configuration $(BuildConfiguration)
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        projects: $(BuildParameters.RestoreBuildProjects)
        arguments: --configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)
        zipAfterPublish: True
    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      condition: succeededOrFailed()
      inputs:
        PathtoPublish: $(build.artifactstagingdirectory)
        TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'

- stage: deploy_to_test
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'development'))
  jobs:
    - job: deployToAppService
      displayName: 'DeployToAppService - Test'
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'drop'
          targetPath: '$(Pipeline.Workspace)'
      - task: AzureWebApp@1
        inputs:
          azureSubscription: 'Pay-As-You-Go(1)(57f4859b-8037-4106-ac17-61520b9de19b)'
          appType: 'webApp'
          appName: 'yamlpocapi-test'
          package: '$(Pipeline.Workspace)/**/*.zip'
          appSettings: '-ASPNETCORE_ENVIRONMENT "Test"'
          deploymentMethod: 'auto'

- stage: wait_for_uat_approval
  condition: and(always(), eq(variables['Build.SourceBranchName'], 'releases/*'))
  pool: server
  jobs:
    - job: waitForApproval
      displayName: 'Wait for Approval'
      timeoutInMinutes: 4320
      steps:
      - task: ManualValidation@0
        timeoutInMinutes: 1440
        inputs:
          notifyUsers: 'joe.ipe@hotmail.com'
          instructions: 'Please validate the test end deployment'
          onTimeout: reject

- stage: deploy_to_uat
  condition: and(always(), eq(variables['Build.SourceBranchName'], 'releases/*'))
  jobs:
    - job: deployToAppService
      displayName: 'DeployToAppService - UAT'
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'drop'
          targetPath: '$(Pipeline.Workspace)'
      - task: AzureWebApp@1
        inputs:
          azureSubscription: 'Pay-As-You-Go(1)(57f4859b-8037-4106-ac17-61520b9de19b)'
          appType: 'webApp'
          appName: 'yamlpocapi-uat'
          package: '$(Pipeline.Workspace)/**/*.zip'
          appSettings: '-ASPNETCORE_ENVIRONMENT "UAT"'
          deploymentMethod: 'auto'

- stage: wait_for_prod_approval
  condition: and(always(), eq(variables['Build.SourceBranchName'], 'master'))
  pool: server
  jobs:
    - job: waitForApproval
      displayName: 'Wait for Approval'
      timeoutInMinutes: 4320
      steps:
      - task: ManualValidation@0
        timeoutInMinutes: 1440
        inputs:
          notifyUsers: 'joe.ipe@hotmail.com'
          instructions: 'Please validate the uat end deployment'
          onTimeout: reject

- stage: deploy_to_prod
  condition: and(always(), eq(variables['Build.SourceBranchName'], 'master'))
  jobs:
    - job: deployToAppService
      displayName: 'DeployToAppService - Prod'
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'drop'
          targetPath: '$(Pipeline.Workspace)'
      - task: AzureWebApp@1
        inputs:
          azureSubscription: 'Pay-As-You-Go(2)(57f4859b-8037-4106-ac17-61520b9de19b)'
          appType: 'webApp'
          appName: 'yamlpocapi'
          package: '$(Pipeline.Workspace)/**/*.zip'
          appSettings: '-ASPNETCORE_ENVIRONMENT "Production"'
          deploymentMethod: 'auto'