variables:
- name: BuildParameters.RestoreBuildProjects
  value: '**/*.csproj'
- name: BuildParameters.TestProjects
  value: '**/*[Tt]ests/*.csproj'
trigger:
  branches:
    include:
    - refs/heads/master
    - development
name: $(date:yyyyMMdd)$(rev:.r)
stages:
- stage: Check
  jobs:
  - job: Job_1
    displayName: Agent job 1
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo "name is $(Build.SourceBranchName)"
    - script: echo "name is $variables['Build.SourceBranchName']"
    - script: echo "name is variables['Build.SourceBranchName']"

- stage: Condition
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'development'))
  jobs:
  - job: Job_1
    displayName: Agent job 1
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo "name is $(Build.SourceBranchName)"