# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
    - job: build
      steps:
      - script: dotnet build
        displayName: 'Build'

      - script: dotnet publish -o $(build.artifactStagingDirectory)
        displayName: 'Publish'

      - task: PublishPipelineArtifact@1
        displayName: Publish Artifact
        inputs:
          # targetPath: '$(Pipeline.Workspace)'
          targetPath: '$(build.artifactstagingdirectory)'
          artifact: 'drop'
          publishLocation: 'pipeline'

- stage: deploy_to_test
  jobs:
    - job: deployToAppService
      displayName: 'DeployToAppService - Test'
      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'drop'
          targetPath: '$(Pipeline.Workspace)'
      
      - task: AzureWebApp@1
        inputs:
          azureSubscription: 'Pay-As-You-Go(1)(57f4859b-8037-4106-ac17-61520b9de19b)'
          appType: 'webApp'
          appName: 'yamlpocapi-test'
          package: '$(System.DefaultWorkingDirectory)/**/*.zip'
          appSettings: '-ApiSettings "Test YAML"'
          deploymentMethod: 'auto'