variables:
- name: BuildParameters.RestoreBuildProjects
  value: '**/*.csproj'
- name: BuildParameters.TestProjects
  value: '**/*[Tt]ests/*.csproj'
trigger:
  branches:
    include:
    - refs/heads/master
    - refs/heads/develop
    - refs/heads/release/*
name: $(date:yyyyMMdd)$(rev:.r)
stages:

- stage: vault_test
  condition: and(always(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
    - job: vaultTest
      displayName: 'VaultTest - Prod'
      steps:
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: 'Pay-As-You-Go(4)(57f4859b-8037-4106-ac17-61520b9de19b)'
          KeyVaultName: 'yamlpocvault'
          SecretsFilter: '*'
          RunAsPreJob: false
      - task: CmdLine@2
        inputs:
          script: 'echo $(SuperSecret) > secret.txt'
      - task: CopyFiles@2
        inputs:
          Contents: 'secret.txt'
          TargetFolder: '$(build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'