# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
    - job: build
      steps:
      - script: dotnet build
        displayName: 'Build'

      - script: dotnet publish -o $(build.artifactStagingDirectory)
        displayName: 'Publish'

      - task: PublishPipelineArtifact@1
        displayName: Publish Artifact
        inputs:
          # targetPath: '$(Pipeline.Workspace)'
          targetPath: '$(build.artifactstagingdirectory)'
          artifact: 'drop'
          publishLocation: 'pipeline'